# docker-compose.yml
version: '3.8'

services:
  node1:
    build: .
    volumes:
      - ./config/config1.json:/app/config.json
    ports:
      - "30303:30303"  # P2P port
      - "8080:8080"    # API port

  node2:
    build: .
    volumes:
      - ./config/config2.json:/app/config.json
    ports:
      - "30304:30303"  # P2P port
      - "8081:8080"    # API port

  node3:
    build: .
    volumes:
      - ./config/config3.json:/app/config.json
    ports:
      - "30305:30303"  # P2P port
      - "8082:8080"    # API port
