# docker-compose.yml
version: '3.8'

services:
  node1:
    build: .
    container_name: node1
    volumes:
      - ./config/config1.json:/app/config.json
    ports:
      - "30303:30303"
      - "8080:8080"
    networks:
      blockchain_network:
        aliases:
          - node1
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "30303"]
      interval: 10s
      timeout: 5s
      retries: 5

  node2:
    build: .
    container_name: node2
    volumes:
      - ./config/config2.json:/app/config.json
    ports:
      - "30304:30303"
      - "8081:8080"
    networks:
      blockchain_network:
        aliases:
          - node2
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "30303"]
      interval: 10s
      timeout: 5s
      retries: 5

  node3:
    build: .
    container_name: node3
    volumes:
      - ./config/config3.json:/app/config.json
    ports:
      - "30305:30303"
      - "8082:8080"
    networks:
      blockchain_network:
        aliases:
          - node3
    depends_on:
      node2:
        condition: service_healthy

networks:
  blockchain_network:
    driver: bridge
