# docker-compose.yml
version: '3.8'

services:
  node1:
    build: .
    volumes:
      - ./config/config1.json:/app/config.json  # Gắn file config.json vào container
    ports:
      - "30303:30303"  # Mở cổng 30303

  node2:  # Node mới
    build: .
    volumes:
      - ./config/config2.json:/app/config.json  # Gắn file config.json vào container
    ports:
      - "30304:30303"  # Mở cổng 30304

  node3:  # Node mới
    build: .
    volumes:
      - ./config/config3.json:/app/config.json  # Gắn file config.json vào container
    ports:
      - "30305:30303"  # Mở cổng 30305
